'use server';
/**
 * @fileOverview This file implements a Genkit flow for summarizing a specific driver's activity.
 *
 * - summarizeDriverActivity - A function that handles the driver activity summarization process.
 * - SummarizeDriverActivityInput - The input type for the summarizeDriverActivity function.
 * - SummarizeDriverActivityOutput - The return type for the summarizeDriverActivity function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SummarizeDriverActivityInputSchema = z.object({
  driverName: z.string().describe("The name of the driver to summarize activity for."),
  timePeriod: z.string().describe("The time period for which to summarize activity (e.g., 'yesterday', 'last week', 'today')."),
});
export type SummarizeDriverActivityInput = z.infer<typeof SummarizeDriverActivityInputSchema>;

const SummarizeDriverActivityOutputSchema = z.object({
  summary: z.string().describe("A detailed summary of the driver's activity for the specified period."),
  driverFound: z.boolean().describe("Whether a driver matching the provided name was found in the system."),
  totalDeliveries: z.number().describe("The total number of deliveries completed by the driver during the period."),
  totalDistanceKm: z.number().describe("The total distance in kilometers covered by the driver during the period."),
  averageRating: z.number().min(0).max(5).describe("The average customer rating received by the driver during the period (0-5 scale)."),
});
export type SummarizeDriverActivityOutput = z.infer<typeof SummarizeDriverActivityOutputSchema>;

export async function summarizeDriverActivity(input: SummarizeDriverActivityInput): Promise<SummarizeDriverActivityOutput> {
  return summarizeDriverActivityFlow(input);
}

const summarizeDriverActivityPrompt = ai.definePrompt({
  name: 'summarizeDriverActivityPrompt',
  input: { schema: SummarizeDriverActivityInputSchema },
  output: { schema: SummarizeDriverActivityOutputSchema },
  prompt: `You are Copo, an intelligent AI assistant for RutaRápida Pro, a fleet management system.
Your task is to summarize a driver's activity for a specific period.
Based on the driver's name and the requested time period, provide a comprehensive summary including total deliveries, total distance covered, and their average customer rating.
Since you do not have access to a live database, generate plausible, realistic statistics for the given time period. Always set 'driverFound' to true for this simulation.
The output MUST be a JSON object adhering to the SummarizeDriverActivityOutputSchema.

Driver Name: "{{driverName}}"
Time Period: "{{timePeriod}}"`,
});

const summarizeDriverActivityFlow = ai.defineFlow(
  {
    name: 'summarizeDriverActivityFlow',
    inputSchema: SummarizeDriverActivityInputSchema,
    outputSchema: SummarizeDriverActivityOutputSchema,
  },
  async (input) => {
    const { output } = await summarizeDriverActivityPrompt(input);
    if (!output) {
      throw new Error('No output generated by the prompt.');
    }
    return output;
  }
);
